# Generated by Django 3.0.5 on 2020-04-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
